### PR TITLE
Gemfile.lock: Check into version control

### PR DESCRIPTION
**Pull request by basil-conto**
The main change in this PR is to start versioning the `Gemfile.lock` file.

Other changes include:
- Cleaning up the `.gitignore` file
- Adding a note on how to `bundle install` locally

These are all split into individual commits, which you are invited to inspect separately or squash as you see fit.

WDYT?
Thanks.

### CODE REVIEW

**Comment by SolalPirelli** [comment]
I removed the gems altogether in my restructuring branch which @shardulc is currently dealing with (since I messed up the branching), it turns out they're not actually needed to just have the theme (only for stuff like "fetch the repo description from GitHub based on the git repo's remote", which we don't use). So I think this is no longer needed -- sorry.

**Comment by vinitra** [comment]
We should still add Basil into the list of contributors though! I'll add him in the search PR. :)

**Comment by basil-conto** [comment]
> So I think this is no longer needed -- sorry.

No worries at all!  I'll leave this PR open for now as a reminder to check that your branch has included the `.gitignore` cleanups as well - but feel free to close it when you're satisfied that that's the case (or no longer needed).

> We should still add Basil into the list of contributors though! I'll add him in the search PR. :)

Thanks, but I don't actually care about attribution!  I was just following the README (and am happy to take ~blame~ responsibility ;).

**Comment by SolalPirelli** [comment]
Good point about the gitignore. Do you know what `.jekyll-cache/` is supposed to be? I'm pretty sure I saw it being deleted recently when doing a git clean so maybe we should keep it?

**Comment by basil-conto** [comment]
> Good point about the gitignore. Do you know what `.jekyll-cache/` is supposed to be? I'm pretty sure I saw it being deleted recently when doing a git clean so maybe we should keep it?

If the directory is created on your system, then of course we should keep ignoring it.  Neither @shardulc nor I had the directory on our systems.  I wonder if we're running in `safe` mode (I have no idea what this means in practice)?  https://jekyllrb.com/docs/configuration/options/

**Comment by shardulc** [comment]
Tried again from a clean build, `.jekyll-cache` is created on my system too, but automatically has a "*" `.gitignore` inside the directory so we don’t have to add it to the top-level one. Removing the rest of them and anchoring at root seems good, and as Solal said, the gem-related changes are unfortunately no longer necessary. Merging as part of `shardulc/restructuring` so closing here.

**Pull request closed without merging**
